name: Docker Login

on:
  # push:
  #   branches: main
  workflow_dispatch:

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: demo.goharbor.io
          username: admin
          password: Harbor12345
