name: ci

on:
  push:
    branches: main

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: harbor.192.168.9.78.nip.io:30443
          username: admin
          password: Harbor12345
