name: Image push and sign
on:
  # push:
  #   branches: [ "main" ]
  # 수동으로 트리거줄때 해당 명령어
  workflow_dispatch:

env:
  REGISTRY: demo.goharbor.io
  REGISTRY_USER: admin
  REGISTRY_PASSWORD: Harbor12345

jobs:
  build:
    name: Login and Push Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # login to harbor
      - name: Login to Harbor
        id: login-harbor
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
      # Build Image - we use pull
      - name: Build Image
        id: build-image
        run: |
          podman pull docker.io/nginx:latest
      # push to registry
      - name: Push to Harbor
        id: push-harbor
        uses: redhat-actions/push-to-registry@v2
        with:
          image: nginx
          tags: latest
          registry: ${{ env.REGISTRY }}/library
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
      # cosign installer
      - name: Cosign Installer
        uses: sigstore/cosign-installer@main
      # github actions secret에 있는 cosign key를 disk에 write
      - name: Write signing key to disk
        run: |
          echo ${{ secrets.COSIGN_PRIVATE_KEY }} > cosign.key
          cat cosign.key
        shell: bash
      # cosign sign image
      - name: Sign container image
        run: |
          cosign sign --key cosign.key ${{ env.REGISTRY }}/library/nginx:latest
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}